---
title: "Diet Estimates for Realsies"
author: "Ashlee Mikkelsen"
date: "`r Sys.Date()`"
output: word_document
---

OK. I took the dry run with initial data exploration, TDF and prior calculations using Simmr. Now it's time to do the analysis for real.


```{r}
rm(list = ls())

library(MixSIAR)
library(dplyr)

```

### Load Data

Load in my data of stable isotopes only (no coefficients) as per the MixSIAR package to obtain the global diet estimates

```{r load in data}

mix.global <- load_mix_data(
 filename = "BearIsotopes_MixSIAR.csv",
 iso_names = c("d13C","d15N"),
 factors = NULL,
 fac_random = NULL,
 fac_nested = NULL,
 cont_effects = NULL
)

source <- load_source_data(
 filename = "bears_sources_MIXSIAR.csv",
 source_factors = NULL,
 conc_dep = FALSE,
 data_type = "means",
 mix.global
)

disc <- load_discr_data(
 filename = "bears_discrimination_MixSIAR.csv",
 mix.global
)


```



### Plot data & Pre-run checks

```{r}
plot_data(
 filename = "bear.global_isospace_MixSIAR",
 plot_save_pdf = TRUE,
 plot_save_png = TRUE,
 mix.global,
 source,
 disc
 )

calc_area(source=source,mix=mix.global,discr=disc)

plot_prior(alpha.prior=c(0.07,0.5,0.14,0.3,0.4),source)


# Write the JAGS model file
model_filename <- "MixSIAR_Bear.global_model.txt"   # Name of the JAGS model file
resid_err <- TRUE
process_err <- TRUE
write_JAGS_model(model_filename, resid_err, process_err, mix.global, source)

```



### Run prelim test model
```{r}


GlobalBear.MixSIAR.test <- run_model(
 run = "test",
 mix.global,
 source,
 disc,
 model_filename
 )



```


```{r}
?run_model

GlobalBear.MixSIAR.normal <- run_model(
 run = "normal",
 mix.global,
 source,
 disc,
 model_filename
 )


```


Look at JAGS output

```{r}
?output_JAGS
output_options <- list(summary_save = TRUE,
                       summary_name = "summary_statistics.global",
                       sup_post = FALSE,
                       plot_post_save_pdf = TRUE,
                       plot_post_name = "posterior_density.global",
                       sup_pairs = FALSE,
                       plot_pairs_save_pdf = TRUE,
                       plot_pairs_name = "pairs_plot.global",
                       sup_xy = TRUE,
                       plot_xy_save_pdf = FALSE,
                       plot_xy_name = "xy_plot.global",
                       gelman = TRUE,
                       heidel = FALSE,
                       geweke = TRUE,
                       diag_save = TRUE,
                       diag_name = "diagnostics.global",
                       indiv_effect = FALSE,
                       plot_post_save_png = FALSE,
                       plot_pairs_save_png = FALSE,
                       plot_xy_save_png = FALSE,
                       diag_save_ggmcmc = TRUE)

output_JAGS(GlobalBear.MixSIAR.normal,mix.global, source, output_options)


```






















